/**
 * All user-facing text, in both languages.
 *
 * Errors name the problem and the recovery. Nothing here leaks WebRTC, WebSocket or
 * backend vocabulary: the audience is non-technical.
 */

export type Language = 'en' | 'pt'

const en = {
  // Brand + shell
  tagline: 'Direct file transfer',
  headline: 'Transfer files\nbetween your devices.',
  intro: 'Direct connection. No account. No permanent storage.',
  footer: 'No account · Direct transfer · Rooms expire after 1 hour',
  createdBy: 'Built by',
  language: 'Language',

  // Primary actions
  create: 'Create a room',
  join: 'Join with a code',
  joinRoom: 'Join room',
  codeLabel: 'Room code',
  copyCode: 'Copy room code',
  copied: 'Room code copied',
  cancel: 'Cancel',
  retry: 'Try again',
  retryConnection: 'Try to reconnect',
  close: 'Close',
  dismiss: 'Dismiss message',
  installApp: 'Install app',
  installAppIosBody: 'Tap the Share icon in Safari, then "Add to Home Screen".',
  installAppAndroidBody: 'Open your browser menu (⋮) and choose "Install app" or "Add to Home screen".',
  addFiles: 'Add files',
  chooseFiles: 'Choose files',
  dragAlternative: 'or drag files here',
  queued: 'ready to send',
  removeFromQueue: (name: string) => `Remove ${name} from queue`,
  sendAll: 'Send files',
  sharedTitle: 'Shared in this room',
  sharedEmpty: 'Files you send or receive will be listed here.',
  sent: 'Sent',
  receivedLabel: 'Received',
  peerLeftTitle: 'The other device left the room',
  peerLeftBody: 'The room stays open in case it comes back.',
  rejoinBody: 'Scan or enter this code on the other device to come back to this room.',
  scanToRejoin: 'Scan to rejoin',
  roomExpiresIn: 'Room expires in',

  // Room states
  creatingRoom: 'Waiting for the server…',
  joiningRoom: 'Joining room…',
  roomReady: 'Your room is ready',
  waiting: 'Waiting for another device',
  waitingBody: 'Share the code or scan the QR on your other device.',
  longWaitHint: 'Taking a while? An ad blocker or privacy extension can block the connection — try disabling it for this site.',
  joiningBody: 'Connecting you to the room…',
  connectedTitle: 'Another device joined',
  connectedBody: 'Connected and ready',
  scanToJoin: 'Scan to join this room',
  exitRoom: 'Leave room',

  // Transfer
  transferPanel: 'File transfer',
  modeSend: 'Send',
  modeReceive: 'Receive',
  choose: 'Choose a file',
  dropHint: 'Choose a file or drag it here',
  clearFile: 'Remove selected file',
  clearQueue: 'Clear all',
  send: 'Send file',
  sending: 'Sending',
  sendAnother: 'Send another file',
  receiving: 'Receiving',
  received: 'Received',
  waitingForFile: 'Waiting for a file',
  waitingForFileBody: 'The other device will send it to you.',
  complete: 'Transfer complete',
  arrived: 'Your file arrived safely.',
  otherIsReceiving: 'The other device is ready to receive.',
  otherIsSending: 'The other device is ready to send.',
  bothReceiving: 'Both devices are set to receive. Switch one to Send.',
  receiveModeActive: 'Receive mode',

  // Live clipboard
  noteTitle: 'Shared notepad',
  noteHint: 'Synced live between both devices',
  noteYourText: 'Your text',
  noteTheirText: 'Their text',
  notePlaceholder: 'Type or paste text, a link…',
  noteWaiting: 'Nothing shared yet.',
  copy: 'Copy',

  // Help guide
  help: 'Help',
  helpTitle: 'How to use PyDrop',
  helpStep1Title: '1. Create or join a room',
  helpStep1Body: 'On the device that will receive the file, tap "Create a room". A code and a QR code appear. On the other device, scan that QR code (or tap "Join with a code" and type it in).',
  helpStep2Title: '2. Wait for the connection',
  helpStep2Body: 'As soon as both devices open the same room, they connect directly to each other — no upload, no waiting for a cloud service.',
  helpStep3Title: '3. Send the file',
  helpStep3Body: 'On the sending device, choose the file (or drag it in) and tap "Send file". It arrives on the other device automatically, ready to open.',
  helpNoteTitle: 'Shared notepad',
  helpNoteBody: 'Need to send just a link or a short text, without a file? Use the shared notepad that appears once connected: type in "Your text" and it shows up instantly on the other device.',
  helpFaqTitle: 'Common questions',
  helpFaqInstallQ: 'Do I need to install anything?',
  helpFaqInstallA: 'No. It works directly in the browser on both phone and computer.',
  helpFaqSecurityQ: 'Is it safe?',
  helpFaqSecurityA: 'Yes — files travel directly between the two devices and are never stored on any server.',
  helpFaqExpiryQ: 'Does the room expire?',
  helpFaqExpiryA: 'Yes, after 1 hour. Just create a new one next time.',

  // Device identity
  you: 'YOU',
  otherDevice: 'OTHER DEVICE',
  thisDevice: 'THIS DEVICE',

  // QR
  scanQr: 'Scan QR code',
  scanQrDialog: 'Point your camera at the QR code on the other device.',
  cancelScan: 'Cancel scan',

  // Server preparation
  checkingServer: 'Checking the server…',
  startingServer: 'Waking the server up…',
  startingServerBody: 'The free server sleeps when unused. This takes a few seconds.',
  connectingWs: 'Connecting…',
  serverReady: 'Ready when you are.',
  readyWhenYouAre: 'Ready when you are.',
  elapsedTime: 'Elapsed',

  // Errors — each names the problem and what to do next.
  unableToConnect: 'We could not reach the server.',
  unableToConnectTitle: 'Could not reach the server',
  unableToConnectBody: 'Check your connection and try again. An ad blocker or privacy extension can also block this — try disabling it for this site.',
  roomFull: 'This room already has two devices.',
  roomFullBody: 'Close PyDrop on one of them, or create a new room.',
  roomExpired: 'This room is no longer available.',
  roomExpiredBody: 'Rooms expire after an hour. Create a new one to continue.',
  invalidCode: 'Room codes have eight letters or numbers.',
  invalidQr: 'That QR code is not a PyDrop room.',
  cameraRequired: 'PyDrop needs camera access to scan a room code.',
  cameraRequiredBody: 'Allow camera access, or type the code instead.',
  connectionLostTitle: 'The other device disconnected',
  connectionLostBody: 'Reopen PyDrop there to continue the transfer.',
  reconnectingTitle: 'Reconnecting…',
  reconnectingBody: 'Keep this screen open. This takes a few seconds.',
  // Progress the wait honestly: each line says where we are, never that the
  // link is back before it actually is.
  reconnectingStages: [
    'Reconnecting…',
    'Still trying…',
    'Almost there…',
  ],
  deviceDisconnected: 'Device disconnected',
  fileTooLarge: 'That file is larger than 500 MB.',
  fileTooLargeBody: 'Try a smaller file, or compress it first.',
  transferFailed: 'The transfer did not finish.',
  transferFailedBody: 'The file was not saved. You can try sending it again.',
  confirmLeave: 'A transfer is in progress. Leave anyway?',
  offline: 'You are offline.',
  offlineBody: 'PyDrop needs a connection to pair devices.',
  transferCount: (count: number) => `${count} ${count === 1 ? 'transfer' : 'transfers'}`,
}

const pt: typeof en = {
  tagline: 'Transferência direta de arquivos',
  headline: 'Transfira arquivos\nentre seus dispositivos.',
  intro: 'Conexão direta. Sem conta. Sem armazenamento permanente.',
  footer: 'Sem conta · Transferência direta · Salas expiram em 1 hora',
  createdBy: 'Feito por',
  language: 'Idioma',

  create: 'Criar uma sala',
  join: 'Entrar com um código',
  joinRoom: 'Entrar na sala',
  codeLabel: 'Código da sala',
  copyCode: 'Copiar código',
  copied: 'Código copiado',
  cancel: 'Cancelar',
  retry: 'Tentar novamente',
  retryConnection: 'Tentar reconectar',
  close: 'Fechar',
  dismiss: 'Dispensar mensagem',
  installApp: 'Instalar app',
  installAppIosBody: 'Toque no ícone de Compartilhar do Safari e depois em "Adicionar à Tela de Início".',
  installAppAndroidBody: 'Abra o menu do navegador (⋮) e escolha "Instalar aplicativo" ou "Adicionar à tela inicial".',
  addFiles: 'Adicionar arquivos',
  chooseFiles: 'Escolher arquivos',
  dragAlternative: 'ou arraste os arquivos aqui',
  queued: 'prontos para enviar',
  removeFromQueue: (name: string) => `Remover ${name} da fila`,
  sendAll: 'Enviar arquivos',
  sharedTitle: 'Compartilhado nesta sala',
  sharedEmpty: 'Os arquivos que você enviar ou receber aparecem aqui.',
  sent: 'Enviado',
  receivedLabel: 'Recebido',
  peerLeftTitle: 'O outro dispositivo saiu da sala',
  peerLeftBody: 'A sala continua aberta caso ele volte.',
  rejoinBody: 'Escaneie ou digite este código no outro dispositivo para voltar a esta sala.',
  scanToRejoin: 'Escaneie para voltar',
  roomExpiresIn: 'A sala expira em',

  creatingRoom: 'Aguardando o servidor…',
  joiningRoom: 'Entrando na sala…',
  roomReady: 'Sua sala está pronta',
  waiting: 'Aguardando outro dispositivo',
  waitingBody: 'Compartilhe o código ou escaneie o QR no seu outro dispositivo.',
  longWaitHint: 'Demorando muito? Um bloqueador de anúncios ou extensão de privacidade pode estar bloqueando a conexão — tente desativá-lo para este site.',
  joiningBody: 'Conectando você à sala…',
  connectedTitle: 'Outro dispositivo entrou',
  connectedBody: 'Conectado e pronto',
  scanToJoin: 'Escaneie para entrar nesta sala',
  exitRoom: 'Sair da sala',

  transferPanel: 'Transferência de arquivo',
  modeSend: 'Enviar',
  modeReceive: 'Receber',
  choose: 'Escolher arquivo',
  dropHint: 'Escolha um arquivo ou arraste aqui',
  clearFile: 'Remover arquivo selecionado',
  clearQueue: 'Limpar tudo',
  send: 'Enviar arquivo',
  sending: 'Enviando',
  sendAnother: 'Enviar outro arquivo',
  receiving: 'Recebendo',
  received: 'Recebido',
  waitingForFile: 'Aguardando um arquivo',
  waitingForFileBody: 'O outro dispositivo vai enviar para você.',
  complete: 'Transferência concluída',
  arrived: 'Seu arquivo chegou com segurança.',
  otherIsReceiving: 'O outro dispositivo está pronto para receber.',
  otherIsSending: 'O outro dispositivo está pronto para enviar.',
  bothReceiving: 'Os dois dispositivos estão em receber. Mude um para Enviar.',
  receiveModeActive: 'Modo receber',

  noteTitle: 'Bloco de notas compartilhado',
  noteHint: 'Sincronizado ao vivo entre os dois dispositivos',
  noteYourText: 'Seu texto',
  noteTheirText: 'Texto do outro',
  notePlaceholder: 'Digite ou cole um texto, um link…',
  noteWaiting: 'Nada compartilhado ainda.',
  copy: 'Copiar',

  help: 'Ajuda',
  helpTitle: 'Como usar o PyDrop',
  helpStep1Title: '1. Crie ou entre em uma sala',
  helpStep1Body: 'No dispositivo que vai receber o arquivo, toque em "Criar uma sala". Um código e um QR code vão aparecer. No outro dispositivo, escaneie esse QR code (ou toque em "Entrar com um código" e digite o código).',
  helpStep2Title: '2. Aguarde a conexão',
  helpStep2Body: 'Assim que os dois dispositivos entrarem na mesma sala, eles se conectam diretamente um ao outro — sem upload, sem esperar nenhum serviço de nuvem.',
  helpStep3Title: '3. Envie o arquivo',
  helpStep3Body: 'No dispositivo que está enviando, escolha o arquivo (ou arraste) e toque em "Enviar arquivo". Ele chega automaticamente no outro dispositivo, pronto para abrir.',
  helpNoteTitle: 'Bloco de notas compartilhado',
  helpNoteBody: 'Precisa mandar só um link ou um texto curto, sem ser um arquivo? Use o bloco de notas compartilhado que aparece depois de conectar: digite em "Seu texto" e ele aparece na hora no outro dispositivo.',
  helpFaqTitle: 'Perguntas frequentes',
  helpFaqInstallQ: 'Preciso instalar alguma coisa?',
  helpFaqInstallA: 'Não. Funciona direto no navegador, tanto no celular quanto no computador.',
  helpFaqSecurityQ: 'É seguro?',
  helpFaqSecurityA: 'Sim — os arquivos vão direto de um dispositivo para o outro e nunca ficam guardados em nenhum servidor.',
  helpFaqExpiryQ: 'A sala expira?',
  helpFaqExpiryA: 'Sim, depois de 1 hora. É só criar uma nova na próxima vez.',

  you: 'VOCÊ',
  otherDevice: 'OUTRO DISPOSITIVO',
  thisDevice: 'ESTE DISPOSITIVO',

  scanQr: 'Escanear QR code',
  scanQrDialog: 'Aponte a câmera para o QR code no outro dispositivo.',
  cancelScan: 'Cancelar escaneamento',

  checkingServer: 'Verificando o servidor…',
  startingServer: 'Acordando o servidor…',
  startingServerBody: 'O servidor gratuito dorme quando não é usado. Isso leva alguns segundos.',
  connectingWs: 'Conectando…',
  serverReady: 'Pronto quando você estiver.',
  readyWhenYouAre: 'Pronto quando você estiver.',
  elapsedTime: 'Tempo',

  unableToConnect: 'Não conseguimos falar com o servidor.',
  unableToConnectTitle: 'Não foi possível alcançar o servidor',
  unableToConnectBody: 'Verifique sua conexão e tente novamente. Um bloqueador de anúncios ou extensão de privacidade também pode causar isso — tente desativá-lo para este site.',
  roomFull: 'Esta sala já tem dois dispositivos.',
  roomFullBody: 'Feche o PyDrop em um deles, ou crie uma nova sala.',
  roomExpired: 'Esta sala não está mais disponível.',
  roomExpiredBody: 'Salas expiram depois de uma hora. Crie uma nova para continuar.',
  invalidCode: 'Códigos de sala têm oito letras ou números.',
  invalidQr: 'Esse QR code não é uma sala do PyDrop.',
  cameraRequired: 'O PyDrop precisa da câmera para escanear um código.',
  cameraRequiredBody: 'Permita o acesso à câmera, ou digite o código.',
  connectionLostTitle: 'O outro dispositivo desconectou',
  connectionLostBody: 'Abra o PyDrop nele novamente para continuar a transferência.',
  reconnectingTitle: 'Reconectando…',
  reconnectingBody: 'Mantenha esta tela aberta. Leva alguns segundos.',
  reconnectingStages: [
    'Reconectando…',
    'Ainda tentando…',
    'Quase lá…',
  ],
  deviceDisconnected: 'Dispositivo desconectado',
  fileTooLarge: 'Esse arquivo é maior que 500 MB.',
  fileTooLargeBody: 'Tente um arquivo menor, ou comprima antes.',
  transferFailed: 'A transferência não terminou.',
  transferFailedBody: 'O arquivo não foi salvo. Você pode tentar enviar de novo.',
  confirmLeave: 'Uma transferência está em andamento. Sair mesmo assim?',
  offline: 'Você está sem conexão.',
  offlineBody: 'O PyDrop precisa de conexão para parear dispositivos.',
  transferCount: (count: number) => `${count} ${count === 1 ? 'transferência feita por meio do PyDrop' : 'transferências feitas por meio do PyDrop'}`,
}

export type Copy = typeof en

export const dictionaries: Record<Language, Copy> = { en, pt }
