/**
 * All user-facing text, in both languages.
 *
 * Errors name the problem and the recovery. Nothing here leaks WebRTC, WebSocket or
 * backend vocabulary: the audience is non-technical.
 */

export type Language = 'en' | 'pt'

const en = {
  // Brand + shell
  tagline: 'Direct file transfer',
  headline: 'Transfer files\nbetween your devices.',
  intro: 'Direct connection. No account. No permanent storage.',
  footer: 'No account · Direct transfer · Rooms expire after 1 hour',
  createdBy: 'Built by',
  language: 'Language',

  // Primary actions
  create: 'Create a room',
  join: 'Join with a code',
  joinRoom: 'Join room',
  codeLabel: 'Room code',
  copyCode: 'Copy room code',
  copied: 'Room code copied',
  cancel: 'Cancel',
  retry: 'Try again',
  retryConnection: 'Try to reconnect',
  close: 'Close',
  dismiss: 'Dismiss message',

  // Room states
  creatingRoom: 'Creating your room…',
  joiningRoom: 'Joining room…',
  roomReady: 'Your room is ready',
  waiting: 'Waiting for another device',
  waitingBody: 'Share the code or scan the QR on your other device.',
  connectedTitle: 'Another device joined',
  connectedBody: 'Connected and ready',
  scanToJoin: 'Scan to join this room',
  exitRoom: 'Leave room',

  // Transfer
  transferPanel: 'File transfer',
  modeSend: 'Send',
  modeReceive: 'Receive',
  choose: 'Choose a file',
  dropHint: 'Choose a file or drag it here',
  clearFile: 'Remove selected file',
  send: 'Send file',
  sending: 'Sending',
  sendAnother: 'Send another file',
  receiving: 'Receiving',
  received: 'Received',
  waitingForFile: 'Waiting for a file',
  waitingForFileBody: 'The other device will send it to you.',
  complete: 'Transfer complete',
  arrived: 'Your file arrived safely.',
  otherIsReceiving: 'The other device is ready to receive.',
  otherIsSending: 'The other device is ready to send.',
  bothReceiving: 'Both devices are set to receive. Switch one to Send.',
  receiveModeActive: 'Receive mode',

  // Device identity
  you: 'YOU',
  otherDevice: 'OTHER DEVICE',
  thisDevice: 'THIS DEVICE',

  // Immersive
  enterImmersive: 'Enter immersive mode',
  exitImmersive: 'Exit immersive',
  enterShort: 'Immersive',
  exitShort: 'Exit',
  reduceMotion: 'Reduce motion',
  motionReduced: 'Motion reduced',
  quality: 'Quality',
  qualityHigh: 'High',
  qualityBalanced: 'Balanced',
  qualityReduced: 'Reduced',
  portalLabel: 'Temporary device portal',
  enteringRoom: 'Entering the room…',
  webglMissing: 'Immersive mode needs 3D graphics, which this browser cannot start.',
  webglMissingAction: 'Everything still works in the standard view.',

  // QR
  scanQr: 'Scan QR code',
  scanQrDialog: 'Point your camera at the QR code on the other device.',
  cancelScan: 'Cancel scan',

  // Server preparation
  checkingServer: 'Checking the server…',
  startingServer: 'Waking the server up…',
  startingServerBody: 'The free server sleeps when unused. This takes a few seconds.',
  connectingWs: 'Connecting…',
  serverReady: 'Ready when you are.',
  readyWhenYouAre: 'Ready when you are.',
  elapsedTime: 'Elapsed',

  // Errors — each names the problem and what to do next.
  unableToConnect: 'We could not reach the server.',
  unableToConnectTitle: 'Could not reach the server',
  unableToConnectBody: 'Check your connection and try again.',
  roomFull: 'This room already has two devices.',
  roomFullBody: 'Close PyDrop on one of them, or create a new room.',
  roomExpired: 'This room is no longer available.',
  roomExpiredBody: 'Rooms expire after an hour. Create a new one to continue.',
  invalidCode: 'Room codes have eight letters or numbers.',
  invalidQr: 'That QR code is not a PyDrop room.',
  cameraRequired: 'PyDrop needs camera access to scan a room code.',
  cameraRequiredBody: 'Allow camera access, or type the code instead.',
  connectionLostTitle: 'The other device disconnected',
  connectionLostBody: 'Reopen PyDrop there to continue the transfer.',
  deviceDisconnected: 'Device disconnected',
  fileTooLarge: 'That file is larger than 500 MB.',
  fileTooLargeBody: 'Try a smaller file, or compress it first.',
  transferFailed: 'The transfer did not finish.',
  transferFailedBody: 'The file was not saved. You can try sending it again.',
  confirmLeave: 'A transfer is in progress. Leave anyway?',
  offline: 'You are offline.',
  offlineBody: 'PyDrop needs a connection to pair devices.',
}

const pt: typeof en = {
  tagline: 'Transferência direta de arquivos',
  headline: 'Transfira arquivos\nentre seus dispositivos.',
  intro: 'Conexão direta. Sem conta. Sem armazenamento permanente.',
  footer: 'Sem conta · Transferência direta · Salas expiram em 1 hora',
  createdBy: 'Feito por',
  language: 'Idioma',

  create: 'Criar uma sala',
  join: 'Entrar com um código',
  joinRoom: 'Entrar na sala',
  codeLabel: 'Código da sala',
  copyCode: 'Copiar código',
  copied: 'Código copiado',
  cancel: 'Cancelar',
  retry: 'Tentar novamente',
  retryConnection: 'Tentar reconectar',
  close: 'Fechar',
  dismiss: 'Dispensar mensagem',

  creatingRoom: 'Criando sua sala…',
  joiningRoom: 'Entrando na sala…',
  roomReady: 'Sua sala está pronta',
  waiting: 'Aguardando outro dispositivo',
  waitingBody: 'Compartilhe o código ou escaneie o QR no seu outro dispositivo.',
  connectedTitle: 'Outro dispositivo entrou',
  connectedBody: 'Conectado e pronto',
  scanToJoin: 'Escaneie para entrar nesta sala',
  exitRoom: 'Sair da sala',

  transferPanel: 'Transferência de arquivo',
  modeSend: 'Enviar',
  modeReceive: 'Receber',
  choose: 'Escolher arquivo',
  dropHint: 'Escolha um arquivo ou arraste aqui',
  clearFile: 'Remover arquivo selecionado',
  send: 'Enviar arquivo',
  sending: 'Enviando',
  sendAnother: 'Enviar outro arquivo',
  receiving: 'Recebendo',
  received: 'Recebido',
  waitingForFile: 'Aguardando um arquivo',
  waitingForFileBody: 'O outro dispositivo vai enviar para você.',
  complete: 'Transferência concluída',
  arrived: 'Seu arquivo chegou com segurança.',
  otherIsReceiving: 'O outro dispositivo está pronto para receber.',
  otherIsSending: 'O outro dispositivo está pronto para enviar.',
  bothReceiving: 'Os dois dispositivos estão em receber. Mude um para Enviar.',
  receiveModeActive: 'Modo receber',

  you: 'VOCÊ',
  otherDevice: 'OUTRO DISPOSITIVO',
  thisDevice: 'ESTE DISPOSITIVO',

  enterImmersive: 'Entrar no modo imersivo',
  exitImmersive: 'Sair do imersivo',
  enterShort: 'Imersivo',
  exitShort: 'Sair',
  reduceMotion: 'Reduzir movimento',
  motionReduced: 'Movimento reduzido',
  quality: 'Qualidade',
  qualityHigh: 'Alta',
  qualityBalanced: 'Equilibrada',
  qualityReduced: 'Reduzida',
  portalLabel: 'Portal temporário de dispositivos',
  enteringRoom: 'Entrando na sala…',
  webglMissing: 'O modo imersivo precisa de gráficos 3D, que este navegador não conseguiu iniciar.',
  webglMissingAction: 'Tudo continua funcionando na visão padrão.',

  scanQr: 'Escanear QR code',
  scanQrDialog: 'Aponte a câmera para o QR code no outro dispositivo.',
  cancelScan: 'Cancelar escaneamento',

  checkingServer: 'Verificando o servidor…',
  startingServer: 'Acordando o servidor…',
  startingServerBody: 'O servidor gratuito dorme quando não é usado. Isso leva alguns segundos.',
  connectingWs: 'Conectando…',
  serverReady: 'Pronto quando você estiver.',
  readyWhenYouAre: 'Pronto quando você estiver.',
  elapsedTime: 'Tempo',

  unableToConnect: 'Não conseguimos falar com o servidor.',
  unableToConnectTitle: 'Não foi possível alcançar o servidor',
  unableToConnectBody: 'Verifique sua conexão e tente novamente.',
  roomFull: 'Esta sala já tem dois dispositivos.',
  roomFullBody: 'Feche o PyDrop em um deles, ou crie uma nova sala.',
  roomExpired: 'Esta sala não está mais disponível.',
  roomExpiredBody: 'Salas expiram depois de uma hora. Crie uma nova para continuar.',
  invalidCode: 'Códigos de sala têm oito letras ou números.',
  invalidQr: 'Esse QR code não é uma sala do PyDrop.',
  cameraRequired: 'O PyDrop precisa da câmera para escanear um código.',
  cameraRequiredBody: 'Permita o acesso à câmera, ou digite o código.',
  connectionLostTitle: 'O outro dispositivo desconectou',
  connectionLostBody: 'Abra o PyDrop nele novamente para continuar a transferência.',
  deviceDisconnected: 'Dispositivo desconectado',
  fileTooLarge: 'Esse arquivo é maior que 500 MB.',
  fileTooLargeBody: 'Tente um arquivo menor, ou comprima antes.',
  transferFailed: 'A transferência não terminou.',
  transferFailedBody: 'O arquivo não foi salvo. Você pode tentar enviar de novo.',
  confirmLeave: 'Uma transferência está em andamento. Sair mesmo assim?',
  offline: 'Você está sem conexão.',
  offlineBody: 'O PyDrop precisa de conexão para parear dispositivos.',
}

export type Copy = typeof en

export const dictionaries: Record<Language, Copy> = { en, pt }
